### ISSUE TITLE
Mixing ICMP v4 and v6 config causes a panic

### ISSUE THREAD

**Issue by martinkennelly** [openshift/ingress-node-firewall#205]
Defining an ICMPv4 `protocolConfig` with `protocol` set to `ICMPv6` the following causes a panic:

```yaml
    - action: Deny
      order: 3
      protocolConfig:
        icmp:
          icmpType: 8
        protocol: ICMPv6
```

```
1.6653212685330708e+09	INFO	controllers.IngressNodeFirewall	Attaching firewall interface	{"intf": "eth0"}
I1009 13:14:28.533081  263630 ingress_node_firewall_loader.go:191] Interface eth0 is already attached and managed, skipping
1.6653212685330853e+09	INFO	controllers.IngressNodeFirewall	Loading rules
I1009 13:14:28.533099  263630 ingress_node_firewall_loader.go:109] Ingress node firewall map Info: &{Type:LPMTrie id:9392 KeySize:24 ValueSize:1200 MaxEntries:1024 Flags:1 Name:ingress_node_fi} with FD LPMTrie(ingress_node_fi)#9
1.6653212685331907e+09	INFO	Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference	{"controller": "ingressnodefirewallnodestate", "controllerGroup": "ingressnodefirewall.openshift.io", "controllerKind": "IngressNodeFirewallNodeState", "IngressNodeFirewallNodeState": {"name":"kind-worker","namespace":"ingress-node-firewall-system"}, "namespace": "ingress-node-firewall-system", "name": "kind-worker", "reconcileID": "a8e3e339-4e31-4762-bf4f-9e9e381a3c13"}
2022/10/09 13:14:28 Starting node metrics updater. Metrics will be polled periodically and presented as prometheus metrics
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14ab093]

goroutine 205 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/src/github.com/openshift/ingress-node-firewall/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x16121c0, 0x26356e0})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/openshift/ingress-node-firewall/pkg/ebpf.(*IngNodeFwController).makeIngressFwRulesMap(_, {{_, _, _}, {_, _, _}}, _)
	/go/src/github.com/openshift/ingress-node-firewall/pkg/ebpf/ingress_node_firewall_loader.go:447 +0x553
github.com/openshift/ingress-node-firewall/pkg/ebpf.(*IngNodeFwController).IngressNodeFwRulesLoader(0xc000370040, 0xc000a53560?)
	/go/src/github.com/openshift/ingress-node-firewall/pkg/ebpf/ingress_node_firewall_loader.go:124 +0x4e9
github.com/openshift/ingress-node-firewall/pkg/ebpfsyncer.(*ebpfSingleton).loadIngressNodeFirewallRules(0xc000114d20, 0xc00064f950)
	/go/src/github.com/openshift/ingress-node-firewall/pkg/ebpfsyncer/ebpfsyncer.go:137 +0x65
github.com/openshift/ingress-node-firewall/pkg/ebpfsyncer.(*ebpfSingleton).SyncInterfaceIngressRules(0xc000114d20, 0xc00064f950, 0x0)
	/go/src/github.com/openshift/ingress-node-firewall/pkg/ebpfsyncer/ebpfsyncer.go:107 +0x45e
github.com/openshift/ingress-node-firewall/controllers.(*IngressNodeFirewallNodeStateReconciler).reconcileResource(0x1a7b750?, {0x1a780f0?, 0xc00064f8f0?}, {{{0x1841c27?, 0x28?}, {0xc000371340?, 0x4?}}}, 0xc00066adc0, 0xb0?)
	/go/src/github.com/openshift/ingress-node-firewall/controllers/ingressnodefirewallnodestate_controller.go:94 +0x7e
github.com/openshift/ingress-node-firewall/controllers.(*IngressNodeFirewallNodeStateReconciler).Reconcile(0xc0009f1b60, {0x1a780f0, 0xc00064f8f0}, {{{0xc000652580?, 0x10?}, {0xc000045bb0?, 0x40f327?}}})
	/go/src/github.com/openshift/ingress-node-firewall/controllers/ingressnodefirewallnodestate_controller.go:77 +0x3c5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1a78048?, {0x1a780f0?, 0xc00064f8f0?}, {{{0xc000652580?, 0x173d1c0?}, {0xc000045bb0?, 0xc00041a5d0?}}})
	/go/src/github.com/openshift/ingress-node-firewall/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00012e140, {0x1a78048, 0xc000625480}, {0x166be00?, 0xc0007b4760?})
	/go/src/github.com/openshift/ingress-node-firewall/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:320 +0x33c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00012e140, {0x1a78048, 0xc000625480})
	/go/src/github.com/openshift/ingress-node-firewall/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/src/github.com/openshift/ingress-node-firewall/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:234 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/src/github.com/openshift/ingress-node-firewall/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:230 +0x325
```

Need to get webhook to reject this config but also harden the reconciler code for defence in depth.

**Comment by msherif1234** [comment]
fixed by #209
